export const OUTDOOR_BRANDS = [
    "3T",
    "66 North",
    "8bplus",
    "Aarn",
    "Adidas Terrex",
    "Aftershokz",
    "Aigle",
    "Aku",
    "Alpina",
    "Alstra",
    "Altra",
    "Amok Equipment",
    "Appalachian Gear Company",
    "Arc'teryx",
    "Asivik",
    "Asolo",
    "Aspen",
    "Astral",
    "Atomic",
    "AustriAlpin",
    "Bach",
    "Backcountry",
    "Backpacker's Pantry",
    "Baffin",
    "Bahco",
    "Bajio",
    "Ballop",
    "Base Camp",
    "Bask",
    "Beal",
    "BearVault",
    "Beaver",
    "Bergans",
    "Berghaus",
    "Big Agnes",
    "BioLite",
    "Biscuit",
    "Black Diamond",
    "Black Yak",
    "Blundstone",
    "Boreal",
    "Bridgedale",
    "Brooks",
    "Brunton",
    "Buff",
    "Bushnell",
    "C.A.M.P.",
    "CamelBak",
    "Camp",
    "Canada Goose",
    "Carhartt",
    "Cascade Designs",
    "Cat",
    "Chaco",
    "Chrome",
    "Clif Bar",
    "Climbing Technology",
    "Coal",
    "Cocoon",
    "Coleman",
    "Columbia",
    "Compass",
    "Compressport",
    "Compeed",
    "Contigo",
    "Cordura",
    "Cotopaxi",
    "Craft",
    "Crazy",
    "Creek",
    "Crispi",
    "Crocs",
    "DMM",
    "Dachstein",
    "Dainese",
    "Dakine",
    "Dale of Norway",
    "Darn Tough",
    "Decathlon",
    "Deuter",
    "Devold",
    "Didriksons",
    "Dolomite",
    "Domex",
    "Dometic",
    "Dope Snow",
    "Dr. Martens",
    "Dragon",
    "Dugast",
    "Duluth Trading",
    "Dynafit",
    "Eagle Creek",
    "Eastpak",
    "E9",
    "Ecco",
    "Eddie Bauer",
    "Edelrid",
    "Edelweiss",
    "Eider",
    "Eleveight",
    "Endura",
    "Enlightened Equipment",
    "Eureka!",
    "Evoc",
    "ExOfficio",
    "Exped",
    "Falke",
    "Farm to Feet",
    "Feathered Friends",
    "Ferrino",
    "Fila",
    "Fjällräven",
    "Five Ten",
    "Fizan",
    "Flash",
    "Flow",
    "Flylow",
    "Focus",
    "Force",
    "Fox",
    "G3",
    "GSI Outdoors",
    "Garmont",
    "Garmin",
    "Gear Aid",
    "Geigerrig",
    "Gibbon",
    "Giro",
    "Goal Zero",
    "GoPro",
    "Gossamer Gear",
    "Granite Gear",
    "Gregory",
    "Grivel",
    "Gronell",
    "Grundéns",
    "Guy Cotten",
    "Haglöfs",
    "Hanwag",
    "Hard Rock",
    "Head",
    "Helinox",
    "Helly Hansen",
    "Herschel",
    "Hestra",
    "High Sierra",
    "Highlander",
    "Hilleberg",
    "Hi-Tec",
    "Hoka One One",
    "Holden",
    "Houdini",
    "Howler Brothers",
    "Humangear",
    "Hunter",
    "HydraPak",
    "Hydro Flask",
    "Hyperlite Mountain Gear",
    "Icebreaker",
    "Icelandic",
    "Igloo",
    "Injinji",
    "Inov-8",
    "Isbjörn",
    "Jack Wolfskin",
    "JanSport",
    "Jetboil",
    "Julbo",
    "K2",
    "Kavu",
    "Kayland",
    "Keen",
    "Kelty",
    "Kipsta",
    "Klean Kanteen",
    "Klättermusen",
    "Klymit",
    "Knee",
    "Knog",
    "Kuhl",
    "Kumbre",
    "La Sportiva",
    "Lafuma",
    "Lake",
    "Leki",
    "LifeStraw",
    "Light My Fire",
    "Lizard",
    "Lowa",
    "Lowe Alpine",
    "Lundhags",
    "MSR",
    "Macpac",
    "Mad Rock",
    "Mammut",
    "Marmot",
    "Master",
    "Matador",
    "Mavic",
    "Maxpedition",
    "Meindl",
    "Merrell",
    "Metolius",
    "Millet",
    "Mizuno",
    "Montane",
    "Montbell",
    "Moon",
    "Mountain Equipment",
    "Mountain Hardwear",
    "Mountainsmith",
    "Moy",
    "Mystery Ranch",
    "Nalgene",
    "Nathan",
    "Naturehike",
    "Nemo",
    "New Balance",
    "Nike ACG",
    "Nikwax",
    "Nomad",
    "Norrøna",
    "North Face",
    "Nixon",
    "O'Neill",
    "Oakley",
    "Oboz",
    "Odlo",
    "Olang",
    "Old Navy",
    "Olight",
    "Olukai",
    "Olympus",
    "Omega",
    "On Running",
    "Opinel",
    "Ortlieb",
    "Ortovox",
    "Osprey",
    "Outdoor Research",
    "Outwell",
    "Pacsafe",
    "Pal",
    "Patagonia",
    "Peak Design",
    "Peak Performance",
    "Pelican",
    "Pendleton",
    "Petzl",
    "Picture Organic",
    "Pinguin",
    "Platypus",
    "Poc",
    "Polar",
    "Poler",
    "Prana",
    "Primus",
    "Pro",
    "Puma",
    "Quechua",
    "Rab",
    "Raidlight",
    "Rapha",
    "Red Chili",
    "Red Fox",
    "Reebok",
    "Reef",
    "Regatta",
    "Rei Co-op",
    "Ren",
    "Revelate Designs",
    "Rhino",
    "Ridgeline",
    "Ritte",
    "Robens",
    "Rock Experience",
    "Rohner",
    "Rossignol",
    "Rotauf",
    "Rox",
    "Royal Robbins",
    "Ruffwear",
    "Salewa",
    "Salomon",
    "Salt",
    "Sanuk",
    "Saucony",
    "Sawyer",
    "Scarpa",
    "Schöffel",
    "Scott",
    "Sea to Summit",
    "SealLine",
    "Sealskinz",
    "Sherpa",
    "Shimano",
    "Sidas",
    "Sierra Designs",
    "Sig",
    "Silva",
    "Simms",
    "Singing Rock",
    "Sinner",
    "Sigg",
    "Six Moon Designs",
    "Skogstad",
    "Slackline",
    "Smartwool",
    "Smith",
    "Snow Peak",
    "Sorel",
    "Source",
    "Spanx",
    "Speedo",
    "Spider",
    "Spyder",
    "Stanley",
    "Steripen",
    "Stio",
    "Stone Island",
    "Storm",
    "Strider",
    "Suunto",
    "Sweet Protection",
    "Swift",
    "Swiss Gear",
    "Teva",
    "Tactical",
    "Tatonka",
    "Tecnica",
    "Tent",
    "Terra Nova",
    "Terrex",
    "Therm-a-Rest",
    "Thule",
    "Tic",
    "Timberland",
    "Time",
    "Toad&Co",
    "Toaks",
    "Topo Athletic",
    "Topo Designs",
    "Track",
    "Trek",
    "Trespass",
    "Tretorn",
    "Trangia",
    "TSL",
    "Tubbs",
    "Ultimate Direction",
    "Under Armour",
    "Uniqlo",
    "Vaude",
    "Vans",
    "Vasque",
    "VauDe",
    "Victorinox",
    "Vingino",
    "Volcom",
    "Vuori",
    "Wacoal",
    "Walkstool",
    "Warm",
    "Warrior",
    "Water",
    "Wenzel",
    "Westcomb",
    "Western Mountaineering",
    "Wild Country",
    "Wildye",
    "Wilson",
    "Wolf",
    "Woolrich",
    "Xero Shoes",
    "Yak",
    "Yeti",
    "Yoko",
    "Zamberlan",
    "Zpacks",
].sort()
